### PR TITLE
Add today's remaining production estimate

### PR DESCRIPTION
**Pull request by koleo9am**
Hi,

  I have added new property energy_production_today_remaining to get production estimate left for rest of today.

Thank You in advance.

Best Regards, Ondrej

### CODE REVIEW

**Comment by koleo9am** [comment]
I am sorry for the lint/flake8 problem.
It should be fine now.

**Comment by koleo9am** [comment]
@klaasnicolaas Hi, what can I do to get this pull request accepted?

Thanks in advance.

**Comment by pandene** [comment]
Be nice to have this, was looking for this feature

**Comment by klaasnicolaas** [comment]
Because this one is simply forgotten 😉

**Review by klaasnicolaas — CHANGES_REQUESTED** [review]
Misses an adjustment of the README, where this new option is mentioned in the list under chapter "data".

**Comment by koleo9am** [comment]
I'll correct it in a minute

**Comment by bilalhp** [comment]
@klaasnicolaas thanks. What does it take to reflect this in HA component?

I have an open feature request:

https://community.home-assistant.io/t/forecast-solar-remaining-energy-production-today/562097

**Comment by koleo9am** [comment]
Current integration to HA requires forecast-solar version 2.2.0.
I have prepared a upgrade of HA integration to use version 2.3.0 and also addition of new sensor for energy_production_today_remaining.
I can prepare pull request for the forecast-solar integration to use energy_production_today_remaining  in the momet new release of forecast-solar is ready.

**Comment by klaasnicolaas** [comment]
My schedule is to review your pull request in the weekend and then merge it, if you are already working on a pull request in core that's fine 👍🏻 FYI: the python package will eventually get version 3.0.0

**Comment by klaasnicolaas** [comment]
One last request, modifying the `example.py` 😉

**Comment by koleo9am** [comment]
> One last request, modifying the `example.py` 😉

Done.

**Comment by bilalhp** [comment]
@klaasnicolaas @koleo9am great collaboration guys! Thanks.

**Review by klaasnicolaas — APPROVED** [review]

**Comment by bilalhp** [comment]
@klaasnicolaas when can we expect a new release?

**Pull request merged**
